### ISSUE TITLE
Write Intro Screen

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/TogethernessHackathonTeam5#22]

**Comment by Koshirikdo** [comment]
You're about to enter a place that defies time as we know it, where you'll work together with another player across two time periods to achieve a common goal.
Choose whether you want to play in the present or in the past and solve puzzles together, in order to advance in this point and click adventure game. Generate an ID and share it with whomever you want to play with them, or join an existing game. Remember: each action in the past has an effect on the future. Will you be able to reach the end?
Welcome to the tower out of time.
